apiVersion: v1
kind: Service
metadata:
  name: bifrost
  labels:
    app: bifrost
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: bifrost
    tier: bifrost
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bifrost
  labels:
    app: bifrost
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bifrost
        tier: bifrost
    spec:
      containers:
      - image: 127.0.0.1:30400/bifrost:latest
        name: bifrost
        ports:
        - containerPort: 80
          name: bifrost
